INSERT INTO category (description) VALUES ('American');
INSERT INTO category (description) VALUES  ('Italian');
INSERT INTO category (description) VALUES  ('Mexican');
INSERT INTO category (description) VALUES  ('Fast food');
INSERT INTO unit_of_measure(description) VALUES ('Teaspoon');
INSERT INTO unit_of_measure(description) VALUES ('Tablespoon');
INSERT INTO unit_of_measure(description) VALUES ('Cap');
INSERT INTO unit_of_measure(description) VALUES ('Pinch');
INSERT INTO unit_of_measure(description) VALUES ('Ounce');
INSERT INTO unit_of_measure(description) VALUES ('each');
INSERT INTO unit_of_measure(description) VALUES ('pounds');
INSERT INTO unit_of_measure(description) VALUES ('dash');